export enum ERROR_CODES {
  INVALID_FORM_KEY = 'INVALID_FORM_KEY',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  GOOGLE_SHEETS_ERROR = 'GOOGLE_SHEETS_ERROR',
  MEMBER_NOT_FOUND_FOR_RENEWAL = 'MEMBER_NOT_FOUND_FOR_RENEWAL',
  EMAIL_NOTIFICATION_ERROR = 'EMAIL_NOTIFICATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
